---
name: Notify discord
on:
  issues:
    types: [opened, closed]
jobs:
  release:
    name: Notify service state
    runs-on: ubuntu-18.04
    steps:
      - name: Service state change
        uses: rjstone/discord-webhook-notify@v1
        if: contains(github.event.issue.label.*.name, 'status')
        with:
          severity: info
          details: Service state changed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
