---
name: Notify discord
on:
  issues:
    types: [opened, closed]
jobs:
  release:
    name: Notify service state
    runs-on: ubuntu-18.04
    steps:
      - name: Service down
        uses: rjstone/discord-webhook-notify@v1
        if: contains(github.event.issue.label.*.name, 'status') and github.event.issue.type == opened
        with:
          severity: info
          details: New service down
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Service back up
        uses: rjstone/discord-webhook-notify@v1
        if: contains(github.event.issue.label.*.name, 'status') and github.event.issue.type == closed
        with:
          severity: info
          details: New service down
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
